const assert=require('node:assert/strict');
global.window={};
require('../static/blocktexx_planner.js');require('../static/blocktexx_costs.js');
const C=window.BlocktexxCosts;
const p={enabled:true,contractor_basis:'hourly',staff_qty:0,staff_hourly:0,paid_hours_week:0,workers_comp_pct:0,super_pct:0,truck_insurance_month:0,truck_lease_month:0,fuel_month:0,owned_other_month:0,building_insurance_month:0,building_lease_month:3640/12,contractor_hourly:100,contractor_daily:700,minimum_hours:4,free_wait_minutes:0,demurrage_hourly:100,contractor_other_month:0};
const run=(id,kg,day=0,type='collection')=>({id,activity_type:type,runs_4w:1,planner_slots:[{week:1,day,pickup_kg:kg}],drive_min:60,service_min:0,depot_min:0,prep_min:0,wait_min:0,break_min:0});
const data={cost_profile:p,cost_mode:'contractor',runs:[run('a',100),run('b',300),run('transfer',900,0,'deliver_threadtexx'),run('c',100,1)]};
let d=C.dailySummary(data,1,0);assert.equal(d.kg,400);assert.equal(d.cost,410);assert.equal(d.rate,410/400);
let w=C.periodSummary(data,1);assert.equal(w.kg,500);assert.equal(w.cost,870);assert.equal(w.rate,870/500);assert.equal(C.dailySummary(data,1,2).cost,10);assert.equal(C.dailySummary(data,1,2).rate,null);
assert.ok(Math.abs(C.periodCosts(data,1).totals[1]-w.cost)<1e-8);
assert.ok(Math.abs(C.periodCosts(data,null).totals[1]-C.periodSummary(data).cost)<1e-8);
data.runs[0].planner_slots[0].pickup_kg=null;assert.equal(C.dailySummary(data,1,0).rate,410/300);assert.equal(C.dailySummary(data,1,0).provisional,true);assert.equal(C.periodSummary(data,1).rate,870/400);
data.runs[0].planner_slots[0].pickup_kg=0;assert.equal(C.dailySummary(data,1,0).kg,300);
data.cost_profile.enabled=false;assert.equal(C.dailySummary(data,1,0).cost,null);
data.cost_profile.enabled=true;data.cost_profile.contractor_hourly=null;
d=C.dailySummary(data,1,0);assert.equal(d.cost,10);assert.equal(d.rate,10/300);assert.equal(d.complete,false);assert.equal(d.provisional,true);assert.deepEqual(d.missingCosts,['Contractor base charge']);assert.match(C.summaryRateText(d),/provisional/);
assert.equal(C.summaryRateText(C.dailySummary(data,1,2)),'No pickup kg');
assert.equal(C.periodSummary(data,1).cost,70);assert.equal(C.periodSummary(data,1).rate,70/400);
data.cost_profile.contractor_hourly=100;data.cost_profile.building_insurance_month=null;
d=C.dailySummary(data,1,0);assert.equal(d.cost,410);assert.equal(d.rate,410/300);assert.deepEqual(d.missingCosts,['Building insurance']);
data.cost_profile.building_insurance_month=0;data.cost_profile.building_lease_month=0;data.cost_profile.contractor_hourly=0;
d=C.dailySummary(data,1,0);assert.equal(d.rate,0);assert.equal(d.provisional,false);
data.runs[0].drive_min=null;assert.equal(C.dailySummary(data,1,0).provisional,true);assert.equal(C.dailySummary(data,1,0).rate,0);
console.log('Daily kg: shared minimum, transfer exclusion, overheads, weighted rates, missing/zero weights and incomplete prices passed.');
require('../static/blocktexx_weights.js');
const W=window.BlocktexxWeights,model={sites:[{id:'s1'},{id:'s2'}],weight_history:{pickups:[{site_id:'s1',kg:300},{site_id:'s1',kg:500},{site_id:'s2',kg:100},{site_id:'',kg:999}]}};
W.sync(model);assert.equal(model.sites[0].sample_pickup_kg,400);
const sr={site_ids:['s1','s2']};assert.equal(W.pickup(sr,{},model.sites).kg,500);
assert.equal(W.pickup(sr,{pickup_by_site:{s1:0}},model.sites).kg,100);
model.sites[0].scenario_pickup_kg=1000;assert.equal(W.pickup(sr,{},model.sites).kg,1100);
assert.equal(W.pickup(sr,{pickup_kg:50},model.sites).kg,50);
assert.equal(W.pickup({activity_type:'collect_decomm'}, {pickup_kg:999}, model.sites).kg,0);
assert.equal(W.pickup({site_ids:['missing']},{},model.sites).missing,1);
const be=C.breakEven({selling_per_kg:.5},{complete:true,missing:0,cost:1000,kg:1500});assert.equal(be.target,2000);assert.equal(be.result,-250);
assert.equal(C.breakEven({selling_per_kg:0},{complete:true,missing:0,cost:1000,kg:0}).result,-1000);
assert.equal(C.breakEven({selling_per_kg:.5},{complete:false,missing:0,cost:1000,kg:1500}).result,null);
console.log('Historical averages, per-customer and per-occurrence scenarios, zero overrides and break-even arithmetic passed.');

